# Generated by Django 4.2 on 2026-05-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_sprint_ticket_sprint"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="due_date",
            field=models.DateField(
                blank=True, help_text="When does this need to be done?", null=True
            ),
        ),
    ]
