# Generated by Django 4.2 on 2026-05-16 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0005_ticket_due_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="cancellation_reason",
            field=models.TextField(
                blank=True, help_text="Why was this ticket cancelled?"
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cancelled_tickets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("todo", "To Do"),
                    ("in_progress", "In Progress"),
                    ("in_review", "In Review"),
                    ("done", "Done"),
                    ("cancelled", "Cancelled"),
                ],
                default="todo",
                max_length=20,
            ),
        ),
    ]
