# Generated by Django 4.2 on 2026-09-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0006_ticket_cancellation_reason_ticket_cancelled_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="due_date",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="When does this need to be done?",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("todo", "To Do"),
                    ("in_progress", "In Progress"),
                    ("in_review", "In Review"),
                    ("done", "Done"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="todo",
                max_length=20,
            ),
        ),
    ]
